name: rick_and_morty_characters
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"


flutter_icons:
  image_path_android: "assets/ic_ios.png"
  image_path_ios: "assets/ic_ios.png"
  android: true 
  ios: true 
  adaptive_icon_background: "assets/ic_background.png" 
  adaptive_icon_foreground: "assets/ic_foreground.png" 



flutter:
  assets:
    - assets/main_loader.gif
    - assets/secondary_loader.gif
    - assets/portal.gif

 
  uses-material-design: true

  